"""empty message

Revision ID: a931a8b294fb
Revises: 
Create Date: 2020-07-13 14:25:54.754342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a931a8b294fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('product')
    op.drop_table('TopPN')
    op.drop_table('reviewed')
    op.drop_table('reviews')
    op.drop_table('features')
    op.drop_table('reviewer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_reviewer')
    )
    op.create_table('features',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('feature', sa.VARCHAR(), nullable=True),
    sa.Column('pos_count', sa.INTEGER(), nullable=True),
    sa.Column('neg_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.id'], name='fk_features_pid_product'),
    sa.PrimaryKeyConstraint('id', name='pk_features')
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rid', sa.INTEGER(), nullable=True),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.Column('post_date', sa.VARCHAR(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('helpful', sa.INTEGER(), nullable=True),
    sa.Column('page', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.id'], name='fk_reviews_pid_product'),
    sa.ForeignKeyConstraint(['rid'], ['reviewer.id'], name='fk_reviews_rid_reviewer'),
    sa.PrimaryKeyConstraint('id', name='pk_reviews')
    )
    op.create_table('reviewed',
    sa.Column('reviewer_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_reviewed_product_id_product'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewer.id'], name='fk_reviewed_reviewer_id_reviewer')
    )
    op.create_table('TopPN',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('pos_review_id', sa.INTEGER(), nullable=True),
    sa.Column('neg_review_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['neg_review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['product.id'], ),
    sa.ForeignKeyConstraint(['pos_review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pid', name='uq_TopPN_pid')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('last_date', sa.INTEGER(), nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_product')
    )
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('star_1', sa.INTEGER(), nullable=True),
    sa.Column('star_2', sa.INTEGER(), nullable=True),
    sa.Column('star_3', sa.INTEGER(), nullable=True),
    sa.Column('star_4', sa.INTEGER(), nullable=True),
    sa.Column('star_5', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.id'], name='fk_ratings_pid_product'),
    sa.PrimaryKeyConstraint('id', name='pk_ratings'),
    sa.UniqueConstraint('pid', name='uq_ratings_pid')
    )
    # ### end Alembic commands ###
